### ISSUE TITLE
GridIndex Conflicts

### ISSUE THREAD

**Issue by metalax** [AnZhi20/AnZhi20-DSPMod#1]
Your ElectromagneTicturbineProject and SuperMagneticRingProject have Gridindex conflicts with FusionForge and TreePlanterMod.

I'd recommend moving them from 1611 and 1612 to 1111 and 1112 as those are the only two remaining free spaces left on the replicator grid, as you only have the two conflicting items unlike the other mods which have more than two.

**Comment by AnZhi20** [comment]
I'm very sorry I can't do that. Because many players have used my two mods, if I change the position of items and composition table now, the recipe that has been set on the manufacturing platform will be confused. After all, the data is directly written in the archive.

**Comment by AnZhi20** [comment]
I'm very sorry to reply for personal reasons. Then my personal advice for 1111 and 1112 is not to use it. Because the official accelerator's location and composition table are 1110, 1111 and 1112. If the two locations are used, errors will occur due to location conflicts after the official launch of catalyst.

**Comment by AnZhi20** [comment]
So I'm very sorry that I can't change it. At that time, I made full consideration when selecting the location. Moreover, a considerable number of players are already using these two mods. If I change it now, it may cause errors in the archives that have used these two mods.
